---
title: "ToxicR: Continuous Analysis"
---

```{r}
library(ToxicR)
library(tidyverse)
dose <- c(0,62.5,125,250)
obs <- c(1,9,8,14)
n <- c(50,50,50,50)

library(drc)

dat <- data.frame(dose=dose,obs=obs,n=n) %>% mutate(mort=obs/n,surv=1-mort)
mod1 <- drm(surv~dose,weights = n,fct = LN.3(),type = "binomial",data=dat)
plot(mod1,type="all",broken = T)
plot(mod1,type="confidence",add = T)

mod1 <- drm(surv~dose,weights = n,fct = W1.3(),type = "binomial",data=dat)
modelFit(mod1)
plot(mod1,type="all",broken = T)
plot(mod1,type="confidence",add = T)
ED(mod1,c(10,50),interval = "delta")
ED(mod1,c(10,50),interval = "inv")


mod2 <- drm(surv~dose,weights = n,fct = W2.3(),type = "binomial",data=dat)
modelFit(mod1)
summary(mod1)
mod2 <- drm(mort~dose,weights = n,fct = LL.3u(),type = "binomial",data=dat)
modelFit(mod2)
plot(mod2,type="all",broken = T)
plot(mod2,type="confidence",add = T)
```

### create a prior list
```{r}
prior_a <- create_prior_list(normprior(0,3,-20,20),  ## k
                             lnormprior(0,0.25,0,40),  ## alpha
                             lnormprior(0,1.5,0,1000)) ## beta

prior_b <- create_prior_list(normprior(0,2,-20,20),  ## k
                             lnormprior(0,0.5,0,40),  ## alpha
                             lnormprior(0,1.5,0,1000)) ## beta

prior_c <- create_prior_list(normprior(0,2,-20,20),  ## k
                             lnormprior(0,0.75,0,40),  ## alpha
                             lnormprior(0,1.5,0,1000)) ## beta
```

### define the priors for weibull model
```{r}
weibull_one <- create_dichotomous_prior(prior_a,"weibull")
weibull_two <- create_dichotomous_prior(prior_b,"weibull")
weibull_c <- create_dichotomous_prior(prior_b,"weibull")
```

### Fit the model

```{r}
fit_a <- single_dichotomous_fit(dose,obs,n,prior = weibull_one)
summary(fit_a)

fit_b <- single_dichotomous_fit(dose,obs,n,prior = weibull_two)
fit_c <- single_dichotomous_fit(dose,obs,n,prior = weibull_c)
```

### Fit the MLE method!
```{r}
fit_d <- single_dichotomous_fit(dose,obs,n,fit_type = "mle",model_type = "weibull",BMR=0.1)
summary(fit_d)
```

### Plot the model output

```{r}

p1 <- plot(fit_a)
p2 <- plot(fit_b)
p3 <- plot(fit_c)
library(patchwork)
p1+p2+p3
```

